# Generated by Django 5.2.10 on 2026-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('push', 'Push'), ('pull', 'Pull'), ('strength', 'Strength'), ('cardio', 'Cardio')], max_length=20, null=True)),
                ('muscle_group', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs')], max_length=40, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
